-- MySQL Script generated by MySQL Workbench
-- Fri Dec 27 00:20:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema newapp-library-1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema newapp-library-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `newapp-library` ;
USE `newapp-library` ;

-- -----------------------------------------------------
-- Table `newapp-library`.`t_clients_ies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_clients_ies` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ies_nombre` VARCHAR(255) NOT NULL,
  `ies_codmod` VARCHAR(255) NULL DEFAULT NULL,
  `ies_anexo` VARCHAR(255) NULL DEFAULT NULL,
  `ies_ruc` VARCHAR(255) NULL DEFAULT NULL,
  `ies_alias` VARCHAR(45) NULL DEFAULT NULL,
  `ies_country` VARCHAR(255) NULL DEFAULT NULL,
  `ies_state_region` VARCHAR(45) NULL DEFAULT NULL,
  `ies_province` VARCHAR(45) NULL DEFAULT NULL,
  `ies_district` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `ies_type_admin` ENUM('Privada', 'Pública', 'Convenio Iglesia', 'Convenio Militar') NULL DEFAULT NULL,
  `ies_phone` VARCHAR(45) NULL DEFAULT NULL,
  `ies_email` VARCHAR(255) NULL DEFAULT NULL,
  `ies_contact` VARCHAR(45) NULL DEFAULT NULL,
  `ies_mobile_contact` VARCHAR(45) NULL DEFAULT NULL,
  `ies_url_base` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_careers_career_title_unique` (`ies_nombre` ASC) VISIBLE,
  UNIQUE INDEX `t_careers_career_code_unique` (`ies_codmod` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_people`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_people` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `first_surname` VARCHAR(255) NULL DEFAULT NULL,
  `second_surname` VARCHAR(255) NULL DEFAULT NULL,
  `document_type` TINYINT(3) UNSIGNED NOT NULL DEFAULT 9,
  `document_number` VARCHAR(20) NULL DEFAULT NULL,
  `mobile` VARCHAR(20) NULL DEFAULT NULL,
  `gender` VARCHAR(10) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `is_enabled` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  `email_alternative` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `address_reference` VARCHAR(255) NULL DEFAULT NULL,
  `country` CHAR(4) NULL DEFAULT NULL,
  `state_region` VARCHAR(45) NULL DEFAULT NULL,
  `province` VARCHAR(45) NULL DEFAULT NULL,
  `district` VARCHAR(45) NULL DEFAULT NULL,
  `nationality` CHAR(4) NULL DEFAULT NULL,
  `t_clients_ies_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_mobile_unique` (`mobile` ASC) VISIBLE,
  INDEX `fk_t_people_t_clients_ies_idx` (`t_clients_ies_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_people_t_clients_ies1`
    FOREIGN KEY (`t_clients_ies_id`)
    REFERENCES `newapp-library`.`t_clients_ies` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_careers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_careers` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `career_title` VARCHAR(255) NOT NULL,
  `career_code` VARCHAR(255) NULL DEFAULT NULL,
  `career_alias` VARCHAR(255) NULL DEFAULT NULL,
  `career_related` VARCHAR(255) NULL DEFAULT '',
  `career_notes` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_careers_career_title_unique` (`career_title` ASC) VISIBLE,
  UNIQUE INDEX `t_careers_career_code_unique` (`career_code` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_catalogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_catalogs` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `catalog_name` VARCHAR(255) NOT NULL,
  `catalog_alias` VARCHAR(255) NULL DEFAULT NULL,
  `catalog_display` VARCHAR(255) NULL DEFAULT NULL,
  `catalog_type` VARCHAR(255) NULL DEFAULT NULL,
  `catalog_ico` VARCHAR(255) NULL DEFAULT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_name` (`catalog_name` ASC) VISIBLE,
  UNIQUE INDEX `u_display` (`catalog_display` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_document_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_document_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `document_type_label` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_ebooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_ebooks` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ebook_code` VARCHAR(255) NOT NULL,
  `ebook_isbn` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_title` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_alias` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_display` VARCHAR(50) NOT NULL,
  `ebook_type` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_author` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_editorial` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_year` CHAR(4) NULL DEFAULT NULL,
  `ebook_pages` MEDIUMINT(8) NULL DEFAULT NULL,
  `ebook_front_page` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_details` TEXT NULL DEFAULT NULL,
  `ebook_url` VARCHAR(255) NULL DEFAULT NULL,
  `ebook_file` VARCHAR(255) NULL DEFAULT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `t_catalogs_id` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_code` (`ebook_code` ASC) VISIBLE,
  UNIQUE INDEX `u_display` (`ebook_display` ASC) VISIBLE,
  INDEX `fk_t_ebooks_t_catalogs1_idx` (`t_catalogs_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_ebooks_t_catalogs1`
    FOREIGN KEY (`t_catalogs_id`)
    REFERENCES `newapp-library`.`t_catalogs` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_users` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `avatar` VARCHAR(255) NULL DEFAULT 'media/avatars/blank.png',
  `status` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `logged_in_at` TIMESTAMP NULL DEFAULT NULL,
  `logged_out_at` TIMESTAMP NULL DEFAULT NULL,
  `api_token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP(),
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `salt_decode` VARCHAR(45) NULL DEFAULT NULL,
  `display_name` VARCHAR(45) NULL,
  `user_type` ENUM('User', 'Admin', 'Sysadmin', 'Guest') NULL DEFAULT 'Guest',
  `t_people_id` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `t_users_username_unique` (`username` ASC) VISIBLE,
  UNIQUE INDEX `t_users_email_unique` (`email` ASC) VISIBLE,
  INDEX `fk_t_users_t_people1_idx` (`t_people_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_users_t_people1`
    FOREIGN KEY (`t_people_id`)
    REFERENCES `newapp-library`.`t_people` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_ebooks_views`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_ebooks_views` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ebook_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `status` TINYINT(1) NULL DEFAULT 1,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ebook_id` (`ebook_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `t_ebooks_views_ibfk_1`
    FOREIGN KEY (`ebook_id`)
    REFERENCES `newapp-library`.`t_ebooks` (`id`),
  CONSTRAINT `t_ebooks_views_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `newapp-library`.`t_users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_favorites` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ebook_id` BIGINT(20) UNSIGNED NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NOT NULL,
  `is_favorite` TINYINT(1) NULL DEFAULT 1,
  `status` TINYINT(1) NULL DEFAULT 1,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `ebook_id` (`ebook_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `t_favorites_ibfk_1`
    FOREIGN KEY (`ebook_id`)
    REFERENCES `newapp-library`.`t_ebooks` (`id`),
  CONSTRAINT `t_favorites_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `newapp-library`.`t_users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_roles` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `rolename` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `visible` TINYINT(1) NOT NULL DEFAULT 1,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `level` INT(11) NOT NULL DEFAULT 9,
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `guard_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_sessions` (
  `id` VARCHAR(255) NOT NULL,
  `user_id` BIGINT(20) UNSIGNED NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  `user_agent` TEXT NULL DEFAULT NULL,
  `payload` LONGTEXT NULL DEFAULT NULL,
  `last_activity` INT(11) NULL DEFAULT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `t_sessions_user_id_index` (`user_id` ASC) VISIBLE,
  INDEX `t_sessions_last_activity_index` (`last_activity` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_settings` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_ruc_uid` VARCHAR(25) NOT NULL,
  `client_alias` VARCHAR(255) NULL DEFAULT NULL,
  `client_display` VARCHAR(255) NULL DEFAULT NULL,
  `client_type` VARCHAR(255) NULL DEFAULT NULL,
  `client_logo` VARCHAR(255) NULL DEFAULT NULL,
  `client_weburl` VARCHAR(255) NULL DEFAULT NULL,
  `client_slogan` VARCHAR(255) NULL DEFAULT NULL,
  `client_info` VARCHAR(255) NULL DEFAULT NULL,
  `client_max_users` INT(8) NULL DEFAULT NULL,
  `client_license` VARCHAR(255) NULL DEFAULT NULL,
  `client_date_license` DATE NULL DEFAULT NULL,
  `client_address` VARCHAR(255) NULL DEFAULT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  `created_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `t_clients_ies_id` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `u_ruc_uid` (`client_ruc_uid` ASC) VISIBLE,
  UNIQUE INDEX `u_display` (`client_display` ASC) VISIBLE,
  INDEX `fk_t_settings_t_clients_ies1_idx` (`t_clients_ies_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_settings_t_clients_ies1`
    FOREIGN KEY (`t_clients_ies_id`)
    REFERENCES `newapp-library`.`t_clients_ies` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_users_has_t_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_users_has_t_roles` (
  `t_users_id` BIGINT(20) UNSIGNED NOT NULL,
  `t_roles_id` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`t_users_id`, `t_roles_id`),
  INDEX `fk_t_users_has_t_roles_t_roles1_idx` (`t_roles_id` ASC) VISIBLE,
  INDEX `fk_t_users_has_t_roles_t_users1_idx` (`t_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_users_has_t_roles_t_users1`
    FOREIGN KEY (`t_users_id`)
    REFERENCES `newapp-library`.`t_users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_users_has_t_roles_t_roles1`
    FOREIGN KEY (`t_roles_id`)
    REFERENCES `newapp-library`.`t_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `newapp-library`.`t_careers_has_t_clients_ies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `newapp-library`.`t_careers_has_t_clients_ies` (
  `t_careers_id` INT(10) UNSIGNED NOT NULL,
  `t_clients_ies_id` INT(10) UNSIGNED NOT NULL,
  `t_catalogs_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`t_careers_id`, `t_clients_ies_id`, `t_catalogs_id`),
  INDEX `fk_t_careers_has_t_clients_ies_t_clients_ies1_idx` (`t_clients_ies_id` ASC) VISIBLE,
  INDEX `fk_t_careers_has_t_clients_ies_t_careers1_idx` (`t_careers_id` ASC) VISIBLE,
  INDEX `fk_t_careers_has_t_clients_ies_t_catalogs1_idx` (`t_catalogs_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_careers_has_t_clients_ies_t_careers1`
    FOREIGN KEY (`t_careers_id`)
    REFERENCES `newapp-library`.`t_careers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_careers_has_t_clients_ies_t_clients_ies1`
    FOREIGN KEY (`t_clients_ies_id`)
    REFERENCES `newapp-library`.`t_clients_ies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_careers_has_t_clients_ies_t_catalogs1`
    FOREIGN KEY (`t_catalogs_id`)
    REFERENCES `newapp-library`.`t_catalogs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
